### ISSUE TITLE
Platform.io library out of date

### ISSUE THREAD

**Issue by ds196** [Lynxmotion/LSS_Library_Arduino#10]
Hello,

I have ran into a few issues using this library on Platformio, including a default argument on line 1030 in LSS.cpp and needing the SoftwareSerial library. I have noticed that there have been commits in this repository which address these issues, but while this repo is `1.4.3`, the Platformio library is still `1.4.1`. I am requesting that Lynxmotion update the [Platformio library](https://registry.platformio.org/libraries/lynxmotion/Lynxmotion%20Smart%20Servo%20-LSS-) to address these issues.

Thanks,
David

**Comment by RB-ENantel** [comment]
Hi David,

I'm acutally not sure what is Platformio, I don't think we released anything there.
We maintain the GitHub library here and it's published to Arduino Library.

I've just re-released as it was not up to date in Arduino, now it should at 1.4.4

All the best

Eric

**Comment by ds196** [comment]
[PlatformIO](https://platformio.org/) is an embedded software development extension for VS Code, and we currently use it with the Arduino framework to develop code for our Teensy 4.x's. It's like Arduino IDE, but is integrated with VSC and gives you the ability to use features like linting and Copilot. Here's a link to the [LSS PlatformIO library](https://registry.platformio.org/libraries/lynxmotion/Lynxmotion%20Smart%20Servo%20-LSS-).

Best,
David

**Comment by RB-ENantel** [comment]
1.4.4 is now available in Arduino Library Manager

**Comment by ds196** [comment]
Weird, I can see 1.4.4 in the library manager in Arduino IDE

**Comment by RB-ENantel** [comment]
Sorry, when I type too fast sometimes "NOW" become "NOT" .. happens to me all the time.

**Comment by ds196** [comment]
Lol, that makes more sense

Is there any chance that the PlatformIO library can be updated aswell? Do you know who might have been maintaining Lynxmotion's libraries over there?

**Comment by RB-ENantel** [comment]
I don't know who maintain that PlatformIO, Isn't it automatically linked to GitHub ?
On that platform I can see SP and CM as people who maintain but that's on GitHub not on PlatformIO.

**Comment by ds196** [comment]
I don't think it automatically updates from GitHub, the platformio documentation says [here](https://www.amazon.com/Carbon-Fiber-Tube-Wrapped-Surface/dp/B07F63N97P) that you are supposed to run a command (I assume within vscode) every time you wish to update the library in the platformio registry (the online collection of platformio packages). 
Also, platformio probably grabs its maintainer information from the `library.properties`.

**Comment by RB-ENantel** [comment]
Hi ds196,

Those look like very nice carbon fiber tubes.
However I'm not the one who created and maintained the platform.io so I can't do much.

Best regards,
