### ISSUE TITLE
Method parameters should be: const char *

### ISSUE THREAD

**Issue by KurtE** [Lynxmotion/LSS_Library_Arduino#3]
Many of the genericRead and genericWrite functions cause compiler warnings, if you compile using options to show all warnings, including:
```
	static bool genericWrite(uint8_t id, char * cmd);
	static bool genericWrite(uint8_t id, char * cmd, int16_t value);
	static bool genericWrite(uint8_t id, char * cmd, int16_t value, char * parameter, int16_t parameter_value);
	static int16_t genericRead_Blocking_s16(uint8_t id, char * cmd);
	static char * genericRead_Blocking_str(uint8_t id, char * cmd);
```
For example in my test sketch I have:
```
void AllServosOff(void) {
  // Quick and dirty way to do it by broadcast...

  // See if we can do by broadcast
  LSS::genericWrite(LSS_BroadcastID, LSS_ActionLimp); // Tell all of the servos to go limp
}

```
Which gives me a compiler warning, when I am building for a Teensy (4.1 in this case)
`warning: ISO C++ forbids converting a string constant to 'char*'`

These can be fixed by simply marking these functions as: const char*
`	static bool genericWrite(uint8_t id, const char * cmd);`

Note: You should do the same for all similar things like, the similar method that also has:  char * paramete

**Comment by KurtE** [comment]
Note: I have a current local branch with these changes, which later I could do a PR, but first wish to get my test app to compile and run without warnings.

If you wish to take a look before than, it is up at: https://github.com/KurtE/LSS_Library_Arduino/tree/compiler_warnings

**Comment by KurtE** [comment]
I have not fixed all of the compiler warnings in this library, as there are a reasonable number of them. 

Things like the usage of volatile.  It is used in places that I am not sure is correct. 
Like: 
```
bool LSS::getIsFirstPositionEnabled(void)
{
	// Variables
	volatile char * valueStr;

	// Ask servo for status; exit if it failed
	if (!(LSS::genericWrite(this->servoID, LSS_QueryFirstPosition)))
	{
		LSS::lastCommStatus = LSS_CommStatus_WriteNoBus;
		return (false);
	}

	// Read response from servo (as string)
	valueStr = LSS::genericRead_Blocking_str(this->servoID, LSS_QueryFirstPosition);
	if (lastCommStatus == LSS_CommStatus_ReadSuccess)
	{
		// Check if first position is disabled
		return (strcmp(valueStr, LSS_FirstPositionDisabled));
	}
	else
	{
		// Read was not completed;
		return (false);
	}
}
```
It gives me a warning on the strcmp of converting from volatile to const. 
I see no reason: volatile char * valueStr
Needs volatile, unless there is some background ISR that in the background will change what this pointer is pointing too...

Likewise there are several calls to scanf where you pass in variables of type uint8_t or the like and it complains that it may return to you a full: unsigned int value which on Teensy is 32 bits.

**Comment by RB-ENantel** [comment]
PR 4 & 5 completed
