### ISSUE TITLE
Does this library work on Arduinos with an ARM processor such as the Arduino MKR1000?

### ISSUE THREAD

**Issue by ChealsieBains01** [Lynxmotion/LSS_Library_Arduino#9]
I'm using an Arduino MKR board that has an ARM process instead of an AVR processor on it. It runs on 3.3V logic so I've added a level shifter to switch the voltage from 5V to 3.3V on the TX and RX pins. The example codes don't seem to run however. I've tested the library on various other Arduinos and the examples work fine. Is the issue the microcontroller and is there a way I can use this library on the Arduino MKR1000

**Comment by RB-ENantel** [comment]
We never tested on a MKR1000 but you might want to verify the Serial port that it's using.
When we use it on a Teensy we had to move from Serial to Serial1 and you can set that by using the define in the examples:

#define LSS_SERIAL	(Serial)	// ex: Many Arduino boards
//#define LSS_SERIAL	(Serial1)	// ex: Teensy
